{
    "driver\_information": {},
    "cust\_firstName": 'syed',
    cust\_lastName: 'ikram',
    item\_names: \[
    { item: 'veggi biryani', qty: 1, price: '11.99', markupAmount: 0 }
    \],
    delivered\_by: 'delivery app',
    delivery\_fee\_applied: 'PayAsYouGoDelivery\_Fee',
    internal\_order\_status: 'pending',
    promotedBy\_id: 'none',
    investor\_id: 'none',
    delivery\_type: 'home delivery',
    initialSubTotalBeforeDiscount: 11.99,
    markupAmount: 0,
    serviceFees: 5.5,
    tax\_plus\_serviceFees: 8.76,
    tip: 0.6,
    promoOrderAmountAdded\_In\_Total\_charged: 0,
    refunded: false,
    comboPromoOrderPlaced: false,
    whosComboPromoFlagApplied: 'none',
    \_id: '6841948a4e1cb8513404223f',
    email: 'syed1@gmail.com',
    stripe\_transaction\_no: 'ch\_3RWdNbD5ayeTFfpv19M7bCjF',
    order\_no: '06/05/2025-PAY1440679418',
    joined\_order\_no: null,
    delivery\_date: '06/05/2025',
    delivery\_time\_slot: '08:08 am - 08:53 am',
    delivery\_address: '3933 sipp ave, cook, il 80076, usa',
    pickup\_kitchen\_address: null,
    kitchen\_id: '682fba81b09a07376cf30a04',
    kitchen\_name: '1543postmankitchen',
    kitchen\_managingBranchName: '6244dummybranchname',
    kitchen\_geolocation: {
    type: 'Point',
    formattedAddress: '3933 sipp ave, cook, il 80076, usa',
    street: 'sipp avenue',
    city: 'cook',
    state: 'illinois',
    zipcode: '80076',
    country: 'united states',
    county: 'cook county',
    },
    delivery\_price: 20,
    sub\_total: 11.99,
    tax: 3.26,
    total\_charged: 41.35,
    delivery\_charges\_log: {
    pricePaidByKitchen: 0,
    pricePaidByCustomer: 20,
    initialDeliveryPrice: 20
    },
    order\_logs: \[\],
    create\_at: '2025-06-05T12:58:50.673Z',
    \_\_v: 0
    }
    
    